services:
  backend:
    build: ./backend
    ports: 
    - 80:80
    develop:
      watch:
      - action: sync+restart
        path: ./backend
        target: ./app
      - action: rebuild
        path: backend/requirements.txt
    depends_on:
     - db

  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128 mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
