"""initial

Revision ID: 44807a90ac0c
Revises:
Create Date: 2026-08-07 21:43:10.163128

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "44807a90ac0c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("user", "admin", name="userrole"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "blocked", name="userstatus"),
            nullable=False,
        ),
        sa.Column("proverkacheka_token", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_users_created_at_id",
        "users",
        ["created_at", "id"],
        unique=False,
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "aliases",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("alias_name", sa.String(length=255), nullable=False),
        sa.Column("is_regex", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "original_name",
            "alias_name",
            name="uq_aliases_user_pair",
        ),
    )
    op.create_index(
        "ix_aliases_user_created",
        "aliases",
        ["user_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(op.f("ix_aliases_user_id"), "aliases", ["user_id"], unique=False)
    op.create_table(
        "receipts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("qr", sa.String(length=512), nullable=True),
        sa.Column("receipt_number", sa.String(length=32), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.Column("seller_name", sa.String(length=255), nullable=False),
        sa.Column("seller_inn", sa.String(length=12), nullable=True),
        sa.Column("datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_sum", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cashback", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "raw_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                "postgresql",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_receipts_user_created",
        "receipts",
        ["user_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(op.f("ix_receipts_user_id"), "receipts", ["user_id"], unique=False)
    op.create_index(
        "uq_receipts_user_qr",
        "receipts",
        ["user_id", "qr"],
        unique=True,
        postgresql_where=sa.text("qr IS NOT NULL"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"),
        "refresh_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "tags",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_tags_user_name"),
    )
    op.create_index(
        "ix_tags_user_created",
        "tags",
        ["user_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "receipt_items",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_receipt_items_receipt",
        "receipt_items",
        ["receipt_id"],
        unique=False,
    )
    op.create_index("ix_receipt_items_tag", "receipt_items", ["tag_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_receipt_items_tag", table_name="receipt_items")
    op.drop_index("ix_receipt_items_receipt", table_name="receipt_items")
    op.drop_table("receipt_items")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_index("ix_tags_user_created", table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        "uq_receipts_user_qr",
        table_name="receipts",
        postgresql_where=sa.text("qr IS NOT NULL"),
    )
    op.drop_index(op.f("ix_receipts_user_id"), table_name="receipts")
    op.drop_index("ix_receipts_user_created", table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_aliases_user_id"), table_name="aliases")
    op.drop_index("ix_aliases_user_created", table_name="aliases")
    op.drop_table("aliases")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("ix_users_created_at_id", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
