"""add user cursor index

Revision ID: bb2f4b1017a4
Revises: cb84ba503fa6
Create Date: 2026-08-07 17:16:10.808584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2f4b1017a4'
down_revision: Union[str, Sequence[str], None] = 'cb84ba503fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_created_at_id', 'users', ['created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_at_id', table_name='users')
    # ### end Alembic commands ###
